import type {
  CandidateDecision,
  CandidateDecisionInput,
  DecisionType,
  MatchCandidate,
  Need,
  Shortlist
} from "./domain.js";
import { createId, toIsoString } from "./utils.js";

const decisionTypes = [
  "viewed",
  "saved",
  "rejected",
  "requested_contact"
] as const satisfies readonly DecisionType[];
const shortlistDecisionTypes = [
  "requested_contact",
  "saved"
] as const satisfies readonly DecisionType[];

export function recordCandidateDecision(
  input: CandidateDecisionInput,
  now: Date = new Date()
): CandidateDecision {
  validateCandidateDecision(input);

  return {
    ...input,
    note: input.note?.trim() || undefined,
    id: createId("decision"),
    decidedAt: toIsoString(now)
  };
}

export function buildShortlist(
  need: Need,
  matches: readonly MatchCandidate[],
  decisions: readonly CandidateDecision[],
  now: Date = new Date()
): Shortlist {
  const latestByProfile = getLatestDecisionsByProfile(need.id, decisions);
  const items = matches.flatMap((candidate) => {
    const decision = latestByProfile.get(candidate.profile.id);

    if (!isShortlistDecision(decision?.decision)) {
      return [];
    }

    return {
      profileId: candidate.profile.id,
      score: candidate.score,
      decision: decision.decision,
      position: 0,
      reasons: candidate.explanation.reasons
    };
  });

  return {
    id: createId("shortlist"),
    needId: need.id,
    items: sortShortlistItems(items).map((item, index) => ({
      ...item,
      position: index + 1
    })),
    createdAt: toIsoString(now)
  };
}

export function buildRecommendedDecisions(
  need: Need,
  matches: readonly MatchCandidate[],
  now: Date = new Date()
): CandidateDecision[] {
  return matches.map((candidate, index) =>
    recordCandidateDecision(
      {
        needId: need.id,
        profileId: candidate.profile.id,
        decision: recommendedActionToDecision(candidate.recommendedAction),
        matchScore: candidate.score,
        note: index === 0 ? "Autogenerated demo decision for the best current match." : undefined
      },
      now
    )
  );
}

function validateCandidateDecision(input: CandidateDecisionInput): void {
  if (!input.needId.trim()) {
    throw new Error("Candidate decision requires needId");
  }

  if (!input.profileId.trim()) {
    throw new Error("Candidate decision requires profileId");
  }

  if (!isDecisionType(input.decision)) {
    throw new Error(`Unknown candidate decision: ${String(input.decision)}`);
  }
}

function getLatestDecisionsByProfile(
  needId: string,
  decisions: readonly CandidateDecision[]
): Map<string, CandidateDecision> {
  const latestByProfile = new Map<string, CandidateDecision>();

  for (const decision of decisions) {
    if (decision.needId !== needId) {
      continue;
    }

    const current = latestByProfile.get(decision.profileId);

    if (!current || decision.decidedAt >= current.decidedAt) {
      latestByProfile.set(decision.profileId, decision);
    }
  }

  return latestByProfile;
}

function sortShortlistItems(
  items: Omit<Shortlist["items"][number], "position">[]
): Omit<Shortlist["items"][number], "position">[] {
  return [...items].sort((left, right) => {
    if (left.decision !== right.decision) {
      return left.decision === "requested_contact" ? -1 : 1;
    }

    return right.score - left.score;
  });
}

function recommendedActionToDecision(action: MatchCandidate["recommendedAction"]): DecisionType {
  if (action === "request_contact") {
    return "requested_contact";
  }

  if (action === "shortlist") {
    return "saved";
  }

  if (action === "skip") {
    return "rejected";
  }

  return "viewed";
}

function isShortlistDecision(
  decision: DecisionType | undefined
): decision is (typeof shortlistDecisionTypes)[number] {
  return (
    decision !== undefined &&
    (shortlistDecisionTypes as readonly DecisionType[]).includes(decision)
  );
}

function isDecisionType(decision: string): decision is DecisionType {
  return (decisionTypes as readonly string[]).includes(decision);
}
